version: '3.3'

services:

  controller:
    build: ./jenkins-controller
    container_name: jenkins-controller
    ports:
      - "8000:8080"
    volumes:
      - home:/var/jenkins_home
    restart: on-failure
    env_file:
      - ./config/jenkins-controller/.env
    networks:
      - agent_network

  agent:
    build: ./jenkins-agent
    container_name: jenkins-agent
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    env_file:
      - ./config/jenkins-agent/.env
    networks:
      - agent_network

volumes:
  home: {}

networks:
  agent_network:
    driver: bridge